# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def Add_Task(self):
        task = self.Input.text()
        if(task):
                self.List.addItem("%s %s"%("-->",task))
        self.Input.clear()
    def Delete_Task(self):
        Selected_Task = self.List.currentRow()
        self.List.takeItem(self.List.currentRow())
    def ClearAllTasks(self):
        self.List.clear()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 804)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")

        #Add button function
        self.Add = QtWidgets.QPushButton(self.gridWidget,clicked = lambda: self.Add_Task())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Add.sizePolicy().hasHeightForWidth())
        self.Add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        self.Add.setFont(font)
        self.Add.setStyleSheet("QPushButton{background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"border-color:black;\n"
"}\n"
"")
        self.Add.setObjectName("Add")
        self.gridLayout.addWidget(self.Add, 0, 2, 2, 1)
        self.Delete = QtWidgets.QPushButton(self.gridWidget,clicked = lambda : self.Delete_Task())
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Delete.setFont(font)
        self.Delete.setStyleSheet("QPushButton{background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"border-color:black;\n"
"}\n"
"")
        self.Delete.setObjectName("Delete")
        self.gridLayout.addWidget(self.Delete, 0, 3, 1, 2)
        self.Input = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input.sizePolicy().hasHeightForWidth())
        self.Input.setSizePolicy(sizePolicy)
        self.Input.setMaximumSize(QtCore.QSize(1677721, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Input.setFont(font)
        self.Input.setTabletTracking(True)
        self.Input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 236, 220);\n"
"border-radius:10px;}")
        self.Input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Input.setText("")
        self.Input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.Input.setObjectName("Input")
        self.gridLayout.addWidget(self.Input, 0, 1, 2, 1)
        self.ClearAll = QtWidgets.QPushButton(self.gridWidget, clicked = lambda: self.ClearAllTasks())
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        #Clear Button Functions:
        self.ClearAll.setFont(font)
        self.ClearAll.setMouseTracking(True)
        self.ClearAll.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ClearAll.setAcceptDrops(False)
        self.ClearAll.setAutoFillBackground(False)
        self.ClearAll.setStyleSheet("QPushButton{background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"border-color:black;\n"
"}\n"
"")
        self.ClearAll.setObjectName("ClearAll")
        self.gridLayout.addWidget(self.ClearAll, 1, 3, 1, 2)
        self.List = QtWidgets.QListWidget(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)


        #List Widget functions
        self.List.setFont(font)
        self.List.setMouseTracking(True)
        self.List.setAcceptDrops(True)
        self.List.setStyleSheet("QListWidget{\n"
"    background-color: rgb(255, 236, 220);\n"
"    border-radius:10px;\n"
"    \n"
"}")
        self.List.setMovement(QtWidgets.QListView.Free)
        self.List.setFlow(QtWidgets.QListView.TopToBottom)
        self.List.setProperty("isWrapping", False)
        self.List.setResizeMode(QtWidgets.QListView.Fixed)
        self.List.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.List.setViewMode(QtWidgets.QListView.ListMode)
        self.List.setWordWrap(False)
        self.List.setSelectionRectVisible(False)
        self.List.setObjectName("List")
        self.gridLayout.addWidget(self.List, 3, 1, 1, 4)
        self.verticalLayout.addWidget(self.gridWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.List.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("To-Do-List", "To-Do-List"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Add.setShortcut(_translate("MainWindow", "Return"))
        self.Delete.setText(_translate("MainWindow", "Delete"))
        self.Delete.setShortcut(_translate("MainWindow", "Del"))
        self.ClearAll.setText(_translate("MainWindow", "Clear"))
        self.ClearAll.setShortcut(_translate("MainWindow", "Ctrl+Del"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
